# Generated by Django 3.1.7 on 2021-03-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=126, unique=True)),
                ('password', models.CharField(max_length=126)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Bool_User',
            },
        ),
    ]
